apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ga4gh-service-info.fullname" . }}-config
  labels:
    {{- include "ga4gh-service-info.labels" . | nindent 4 }}
data:
  service_info.yaml: |
    {{- .Values.serviceInfo | toYaml | nindent 4 }}
