apiVersion: apps/v1
kind: Deployment
metadata:
  name: ga4gh-SERVICE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ga4gh-SERVICE
  template:
    metadata:
      labels:
        app: ga4gh-SERVICE
    spec:
      containers:
      - name: SERVICE
        image: ga4gh-service-info-SERVICE:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: SERVICE_CONFIG_PATH
          value: /etc/SERVICE/service_info.yaml
        volumeMounts:
        - name: config-volume
          mountPath: /etc/SERVICE
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 5
      volumes:
      - name: config-volume
        configMap:
          name: service-info-config
