id: "org.ga4gh.serviceinfo-service"

name: "Dummy GA4GH ServiceInfo service"

type:
  group: "org.ga4gh"
  artifact: "service-info"
  version: "1.0.0"

organization:
  name: "GA4GH"
  url: "https://www.ga4gh.org"

version: "9.9.9"

# --- Optional fields ---

description: "A reusable service for standardizing GA4GH ServiceInfo metadata."
environment: "dev"
